name: build/test

on:
  push:
    branches: [ "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: install dependencies
      run: .
    - name: build test
      run: make test
    - name: run test
      run: ./test/test

